### PR TITLE
USER SCENARIO 2

### PR DESCRIPTION
**Pull request by braydenmarsh**
# User Scenario 2 DITA map and .ditaval Filters

### Hi Lauren and Eden, 

I hope you both are doing well. 

Since we are structuring our topics for reuse, and my topics could possibly be used alongside both of yours, I want y'all to review my "novice" and "expert" attributes. 

This code cannot automatically merge with the main. I am not sure if we are even supposed to merge with the main. If either of y'all know, please let me know in the comments. 

#### Check:

- If my attributes align with your attributes so that it will make sense when filters are used in reuse scenarios. If you believe something is labeled incorrectly, please let me know (i.e. if something should not have a novice or expert tag).
- review DITAMAP code or any more comments you both may have. 

Thank you for your comments thus far and I look forward to seeing y'alls work.

### CODE REVIEW

**Comment by lhmarlie** [comment]
Hey Brayden, Eden and I have been using the Student Help Forum to ask Dr. Lindgren about the merging issues. 

I think that the .ditaval files might go directly into main as well as the tags?? But I'm not sure, still waiting on Dr. Lindgren's response.

Also, I thought we agreed to only tag the expert data and then a map could run the "exclude expert" and put out a document with all untagged (ie: novice) information...

**Comment by Eden-Miller** [comment]
I know the .ditaval goes in main but I’m not sure about the tagging.

Also, we still tag for both expert and novice.

I’ll have all the editing done tonight so we can create our maps (like we
agreed in class).

Thanks guys!
Eden

**Comment by lingeringcode** [comment]
Resolved the merge issues for you. They were pretty easy conflicts, so good to go.

**Review by Eden-Miller — APPROVED** [review]
Hey Brayden! This looks great to me! Feel free to merge.

**Pull request merged**
