### PR TITLE
Metadata Added to Eden's Files

### PR DESCRIPTION
**Pull request by Eden-Miller**
Hi guys!

Like Lauren, I only marked for expert data because all of our work was created with a novice audience in mind. The only file I created that had expert data was my reference file about LinkedIn supported media. Please let me know if there's any additional places data needs to be added or if something needs to be changed. 

Thanks!
Eden

### CODE REVIEW

**Comment by lhmarlie** [comment]
Hey Eden, your expert tags look good to me but I noticed there was a few novice tags on the t_writing_a_welcome_post. I thought we agreed to just tag expert?

**Comment by Eden-Miller** [comment]
I went ahead and tagged whole sections as novice where I saw fit. We don't have to filter for them. It's just something good to have on record if we come back to these.

**Comment by braydenmarsh** [comment]
Hi Eden. I think that if we are going to tag things, we should be uniform about it. So my question is whether or not I should tag my con, task, and ref topics as novice so that they are uniform with yours? Otherwise, everything looks good.

**Comment by Eden-Miller** [comment]
Only tag something as novice if it doesn't have an expert tag in the copy because the parent/child thing. Let me know if you decide to tag. I'll do Lauren's if she's at work.

**Pull request merged**
